---
version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.12.29

commands:
  setup:
    description: Setup environment
    steps:
      - run:
          name: Install build dependencies
          command: apk add --no-cache ca-certificates git openssh-client
      - checkout

jobs:
  terraform:
    description: Terraform plan
    parameters:
      apply:
        type: boolean
        default: false
    executor:
      name: terraform
    steps:
      - setup
      - restore_cache:
          key: terraform-{{ arch }}-{{ checksum "terraform.tf" }}-
      - run:
          name: Init
          command: terraform init -input=false
      - save_cache:
          key: terraform-{{ arch }}-{{ checksum "terraform.tf" }}-{{ epoch }}
          paths: .terraform
      - run:
          name: Plan
          command: terraform plan -input=false -out=ci -var-file="default.tfvars"
      - when:
          condition: << parameters.apply >>
          steps:
            - deploy:
                name: Apply
                command: terraform apply ci

workflows:
  default:
    jobs:
      - terraform:
          name: plan
          filters:
            branches:
              ignore: master
      - terraform:
          name: apply
          apply: true
          filters:
            branches:
              only: master
